from enum import Enum
from typing import Tuple

from config.types import TechId

# Type alias for all technology tuples (id, amount/level, category)
TechnologyTuple = Tuple[int, int, str]

# OGame page components
class COMPONENTS(Enum):
    OVERVIEW = "overview"
    SUPPLIES = "supplies"
    LFBUILDINGS = "lfbuildings"
    LFRESEARCH = "lfresearch"
    FACILITIES = "facilities"
    TRADER_OVERVIEW = "traderOverview"
    RESEARCH = "research"
    SHIPYARD = "shipyard"
    DEFENSES = "defenses"
    FLEET_DISPATCH = "fleetdispatch"
    GALAXY = "galaxy"
    EMPIRE = "empire"
    MESSAGES = "messages"

# Lifeform classes
class LifeformClass:
    human = 'human'
    mecha = 'mecha'

    @classmethod
    def allLifeforms(cls) -> list[str]:
        return [
            cls.human,
            cls.mecha,
        ]

# Mapping of technology IDs to their respective sections
class TechIdToSection:
    mapping = {
        # Buildings
        "1": COMPONENTS.SUPPLIES,
        "2": COMPONENTS.SUPPLIES,
        "3": COMPONENTS.SUPPLIES,
        "4": COMPONENTS.SUPPLIES,
        "12": COMPONENTS.SUPPLIES,
        "22": COMPONENTS.SUPPLIES,
        "23": COMPONENTS.SUPPLIES,
        "24": COMPONENTS.SUPPLIES,

        # Station
        "14": COMPONENTS.FACILITIES,
        "15": COMPONENTS.FACILITIES,
        "21": COMPONENTS.FACILITIES,
        "31": COMPONENTS.FACILITIES,
        "33": COMPONENTS.FACILITIES,
        "34": COMPONENTS.FACILITIES,
        "44": COMPONENTS.FACILITIES,
        "36": COMPONENTS.FACILITIES,

        # Defense
        "401": COMPONENTS.DEFENSES,
        "402": COMPONENTS.DEFENSES,
        "403": COMPONENTS.DEFENSES,
        "404": COMPONENTS.DEFENSES,
        "405": COMPONENTS.DEFENSES,
        "406": COMPONENTS.DEFENSES,
        "407": COMPONENTS.DEFENSES,
        "408": COMPONENTS.DEFENSES,
        "502": COMPONENTS.DEFENSES,
        "503": COMPONENTS.DEFENSES,

        # Ships
        "204": COMPONENTS.SHIPYARD,
        "205": COMPONENTS.SHIPYARD,
        "206": COMPONENTS.SHIPYARD,
        "207": COMPONENTS.SHIPYARD,
        "215": COMPONENTS.SHIPYARD,
        "211": COMPONENTS.SHIPYARD,
        "213": COMPONENTS.SHIPYARD,
        "214": COMPONENTS.SHIPYARD,
        "218": COMPONENTS.SHIPYARD,
        "219": COMPONENTS.SHIPYARD,
        "202": COMPONENTS.SHIPYARD,
        "203": COMPONENTS.SHIPYARD,
        "208": COMPONENTS.SHIPYARD,
        "209": COMPONENTS.SHIPYARD,
        "210": COMPONENTS.SHIPYARD,
        "212": COMPONENTS.SHIPYARD,
        "217": COMPONENTS.SHIPYARD,

        # Research
        "113": COMPONENTS.RESEARCH,
        "120": COMPONENTS.RESEARCH,
        "121": COMPONENTS.RESEARCH,
        "114": COMPONENTS.RESEARCH,
        "122": COMPONENTS.RESEARCH,
        "106": COMPONENTS.RESEARCH,
        "108": COMPONENTS.RESEARCH,
        "124": COMPONENTS.RESEARCH,
        "123": COMPONENTS.RESEARCH,
        "199": COMPONENTS.RESEARCH,
        "115": COMPONENTS.RESEARCH,
        "117": COMPONENTS.RESEARCH,
        "118": COMPONENTS.RESEARCH,
        "109": COMPONENTS.RESEARCH,
        "110": COMPONENTS.RESEARCH,
        "111": COMPONENTS.RESEARCH,

        # Lifeform Buildings
        "11101": COMPONENTS.LFBUILDINGS,
        "11102": COMPONENTS.LFBUILDINGS,
        "11103": COMPONENTS.LFBUILDINGS,
        "11104": COMPONENTS.LFBUILDINGS,
        "11105": COMPONENTS.LFBUILDINGS,
        "11106": COMPONENTS.LFBUILDINGS,
        "11107": COMPONENTS.LFBUILDINGS,
        "11108": COMPONENTS.LFBUILDINGS,
        "11109": COMPONENTS.LFBUILDINGS,
        "11110": COMPONENTS.LFBUILDINGS,
        "11111": COMPONENTS.LFBUILDINGS,
        "11112": COMPONENTS.LFBUILDINGS,
        "14101": COMPONENTS.LFBUILDINGS,
        "14102": COMPONENTS.LFBUILDINGS,
        "14103": COMPONENTS.LFBUILDINGS,
        "14104": COMPONENTS.LFBUILDINGS,
        "14105": COMPONENTS.LFBUILDINGS,
        "14106": COMPONENTS.LFBUILDINGS,
        "14107": COMPONENTS.LFBUILDINGS,
        "14108": COMPONENTS.LFBUILDINGS,
        "14109": COMPONENTS.LFBUILDINGS,
        "14110": COMPONENTS.LFBUILDINGS,
        "14111": COMPONENTS.LFBUILDINGS,
        "14112": COMPONENTS.LFBUILDINGS,

        # Lifeform Research
        "11201": COMPONENTS.LFRESEARCH,
        "11202": COMPONENTS.LFRESEARCH,
        "11203": COMPONENTS.LFRESEARCH,
        "11204": COMPONENTS.LFRESEARCH,
        "11205": COMPONENTS.LFRESEARCH,
        "11206": COMPONENTS.LFRESEARCH,
        "11207": COMPONENTS.LFRESEARCH,
        "11208": COMPONENTS.LFRESEARCH,
        "11209": COMPONENTS.LFRESEARCH,
        "11210": COMPONENTS.LFRESEARCH,
        "11211": COMPONENTS.LFRESEARCH,
        "11212": COMPONENTS.LFRESEARCH,
        "11213": COMPONENTS.LFRESEARCH,
        "11214": COMPONENTS.LFRESEARCH,
        "11215": COMPONENTS.LFRESEARCH,
        "11216": COMPONENTS.LFRESEARCH,
        "11217": COMPONENTS.LFRESEARCH,
        "11218": COMPONENTS.LFRESEARCH,
        "12201": COMPONENTS.LFRESEARCH,
        "12202": COMPONENTS.LFRESEARCH,
        "12203": COMPONENTS.LFRESEARCH,
        "12204": COMPONENTS.LFRESEARCH,
        "12205": COMPONENTS.LFRESEARCH,
        "12206": COMPONENTS.LFRESEARCH,
        "12207": COMPONENTS.LFRESEARCH,
        "12208": COMPONENTS.LFRESEARCH,
        "12209": COMPONENTS.LFRESEARCH,
        "12210": COMPONENTS.LFRESEARCH,
        "12211": COMPONENTS.LFRESEARCH,
        "12212": COMPONENTS.LFRESEARCH,
        "12213": COMPONENTS.LFRESEARCH,
        "12214": COMPONENTS.LFRESEARCH,
        "12215": COMPONENTS.LFRESEARCH,
        "12216": COMPONENTS.LFRESEARCH,
        "12217": COMPONENTS.LFRESEARCH,
        "12218": COMPONENTS.LFRESEARCH,
        "13201": COMPONENTS.LFRESEARCH,
        "13202": COMPONENTS.LFRESEARCH,
        "13203": COMPONENTS.LFRESEARCH,
        "13204": COMPONENTS.LFRESEARCH,
        "13205": COMPONENTS.LFRESEARCH,
        "13206": COMPONENTS.LFRESEARCH,
        "13207": COMPONENTS.LFRESEARCH,
        "13208": COMPONENTS.LFRESEARCH,
        "13209": COMPONENTS.LFRESEARCH,
        "13210": COMPONENTS.LFRESEARCH,
        "13211": COMPONENTS.LFRESEARCH,
        "13212": COMPONENTS.LFRESEARCH,
        "13213": COMPONENTS.LFRESEARCH,
        "13214": COMPONENTS.LFRESEARCH,
        "13215": COMPONENTS.LFRESEARCH,
        "13216": COMPONENTS.LFRESEARCH,
        "13217": COMPONENTS.LFRESEARCH,
        "13218": COMPONENTS.LFRESEARCH,
        "14201": COMPONENTS.LFRESEARCH,
        "14202": COMPONENTS.LFRESEARCH,
        "14203": COMPONENTS.LFRESEARCH,
        "14204": COMPONENTS.LFRESEARCH,
        "14205": COMPONENTS.LFRESEARCH,
        "14206": COMPONENTS.LFRESEARCH,
        "14207": COMPONENTS.LFRESEARCH,
        "14208": COMPONENTS.LFRESEARCH,
        "14209": COMPONENTS.LFRESEARCH,
        "14210": COMPONENTS.LFRESEARCH,
        "14211": COMPONENTS.LFRESEARCH,
        "14212": COMPONENTS.LFRESEARCH,
        "14213": COMPONENTS.LFRESEARCH,
        "14214": COMPONENTS.LFRESEARCH,
        "14215": COMPONENTS.LFRESEARCH,
        "14216": COMPONENTS.LFRESEARCH,
        "14217": COMPONENTS.LFRESEARCH,
        "14218": COMPONENTS.LFRESEARCH,
        "15201": COMPONENTS.LFRESEARCH,
        "15202": COMPONENTS.LFRESEARCH,
        "15203": COMPONENTS.LFRESEARCH,
        "15204": COMPONENTS.LFRESEARCH,
        "15205": COMPONENTS.LFRESEARCH,
        "15206": COMPONENTS.LFRESEARCH,
        "15207": COMPONENTS.LFRESEARCH,
        "15208": COMPONENTS.LFRESEARCH,
        "15209": COMPONENTS.LFRESEARCH,
        "15210": COMPONENTS.LFRESEARCH,
        "15211": COMPONENTS.LFRESEARCH,
        "15212": COMPONENTS.LFRESEARCH,
        "15213": COMPONENTS.LFRESEARCH,
        "15214": COMPONENTS.LFRESEARCH,
        "15215": COMPONENTS.LFRESEARCH,
        "15216": COMPONENTS.LFRESEARCH,
        "15217": COMPONENTS.LFRESEARCH,
        "15218": COMPONENTS.LFRESEARCH,
    }

    @classmethod
    def get_section(cls, tech_id: TechId) -> COMPONENTS:
        """
        Get the section corresponding to a technology ID.

        Args:
            tech_id (int): The technology ID.

        Returns:
            ComponentType: The section name.
        """
        if tech_id not in cls.mapping:
            raise ValueError(f"Invalid tech_id: {tech_id}. No corresponding section found.")
        section = cls.mapping[tech_id]
        if section not in COMPONENTS:
            raise TypeError(f"Return value {section} is not a valid Section.")
        return section  # Return the section as a COMPONENTS value

